server {
    listen 80;
    server_name developer.photonbolt.xyz;

    root /home/waheed/PhotonBoltXYZ/photon-web-wallet/docs/developer;
    index index.html;

    access_log /var/log/nginx/developer.photonbolt.xyz.access.log;
    error_log /var/log/nginx/developer.photonbolt.xyz.error.log;

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }
}
